name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           docker pull madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 || true
           docker build \
           --cache-from madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 \
           -f src/Dockerfile . \
           -t madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 \
           -t madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10-"$GITHUB_RUN_ID"
           docker push madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10
           docker push madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10-"$GITHUB_RUN_ID"
           docker build -t madnight/alpine-wkhtmltopdf .
