name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           docker pull varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14 || true
           docker build \
           --cache-from varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14 \
           -t varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14 \
           -t varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14-"$GITHUB_RUN_ID"
           docker push varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14
           docker push varunlalan/alpine-wkhtmltopdf-builder:0.12.6-alpine3.14-"$GITHUB_RUN_ID"
           docker build -t varunlalan/alpine-wkhtmltopdf .
